apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: espectaculos
spec:
  type: NodePort
  selector:
    app: espectaculos
  ports:
    - name: http
      port: 80
      targetPort: 8080  # ðŸ‘ˆ el contenedor escucha aquÃ­
      nodePort: 30080
